version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: my-mysql-freelens
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: